import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.midi.MidiUnavailableException;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author wenbozhu
 */
public class Piano_GUI extends javax.swing.JFrame implements KeyListener,MouseListener{

    
    //Sustain - false = off
    protected boolean Sustain = false;
    public RegularSound midisound;
    UserInfo userinfo = new UserInfo();
    /**
     * Creates new form Piano_GUI
     */
    public Piano_GUI() throws MidiUnavailableException {
        midisound = new RegularSound();
        initComponents();
        //setLayout(null);
//        setComponentZOrder(jButton9,1);
//        setComponentZOrder(jButton8,1);
//        setComponentZOrder(jButton1,0);
//        setComponentZOrder(jButton2,0);
//        setComponentZOrder(jButton3,0);
        
        jPanel1.setFocusable(true);
        jPanel1.requestFocus();
        
        
        jButton1.addKeyListener(this);
        jButton1.requestFocus();
        jButton2.addKeyListener(this);
        jButton3.addKeyListener(this);
        jButton4.addKeyListener(this);
        jButton5.addKeyListener(this);
        jButton6.addKeyListener(this);
        jButton7.addKeyListener(this);
        jButton8.addKeyListener(this);
        jButton9.addKeyListener(this);
        jButton10.addKeyListener(this);
        jButton11.addKeyListener(this);
        jButton12.addKeyListener(this);
        jButton1.addMouseListener(this);
        jButton2.addMouseListener(this);
        jButton3.addMouseListener(this);
        jButton4.addMouseListener(this);
        jButton5.addMouseListener(this);
        jButton6.addMouseListener(this);
        jButton7.addMouseListener(this);
        jButton8.addMouseListener(this);
        jButton9.addMouseListener(this);
        jButton10.addMouseListener(this);
        jButton11.addMouseListener(this);
        jButton12.addMouseListener(this);
        jButton14.addMouseListener(this);
        
        jComboBox1.setVisible(false);
        jComboBox2.setVisible(false);
        jButton13.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jButton15 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDialog2 = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jComboBox2 = new javax.swing.JComboBox();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog1.pack();
        jDialog1.setTitle("Login");
        jDialog1.setAlwaysOnTop(true);
        jDialog1.setBounds(new java.awt.Rectangle(422, 323, 422, 323));
        jDialog1.setResizable(false);
        jDialog1.getContentPane().setLayout(null);

        jButton15.setText("Sign in");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton15);
        jButton15.setBounds(180, 220, 75, 23);
        jDialog1.getContentPane().add(jTextField1);
        jTextField1.setBounds(150, 70, 170, 30);
        jDialog1.getContentPane().add(jTextField2);
        jTextField2.setBounds(150, 110, 170, 30);

        jLabel2.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel2.setText("Password:");
        jDialog1.getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 120, 70, 20);

        jLabel4.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel4.setText("Username:");
        jDialog1.getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 80, 70, 20);

        jDialog2.setBounds(new java.awt.Rectangle(357, 110, 357, 110));
        jDialog2.setResizable(false);
        jDialog2.getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel5.setText("The username or the password is not correct");
        jDialog2.getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 10, 330, 30);

        jButton16.setText("OK");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(jButton16);
        jButton16.setBounds(130, 50, 87, 23);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keypressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Keyreleased(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piano.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(6, 4, 144, 148);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitar.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(400, 0, 144, 144);

        jButton12.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jButton12);
        jButton12.setBounds(310, 210, 19, 59);

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jButton9);
        jButton9.setBounds(230, 210, 19, 59);
        jPanel1.add(jButton3);
        jButton3.setBounds(240, 220, 23, 90);

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jButton8);
        jButton8.setBounds(210, 210, 19, 59);
        jPanel1.add(jButton2);
        jButton2.setBounds(220, 220, 23, 90);

        jButton11.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jButton11);
        jButton11.setBounds(290, 210, 19, 59);

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(270, 210, 19, 59);
        jPanel1.add(jButton4);
        jButton4.setBounds(260, 220, 23, 90);
        jPanel1.add(jButton1);
        jButton1.setBounds(200, 220, 23, 90);

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(280, 220, 23, 90);
        jPanel1.add(jButton7);
        jButton7.setBounds(320, 220, 23, 90);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Instrument", "Piano", "Guitar" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(190, 140, 180, 20);

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(300, 220, 23, 90);

        jToggleButton1.setText("Sustain");
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(390, 180, 90, 23);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose a Song", "Song 1", "Song 2" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(200, 360, 150, 20);

        jButton13.setText("Play");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(230, 390, 87, 23);

        jButton14.setText("Sign in");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);
        jButton14.setBounds(230, 40, 75, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keypressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keypressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_keypressed

    private void Keyreleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Keyreleased
        // TODO add your handling code here
        
    }//GEN-LAST:event_Keyreleased

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        switch((jComboBox1.getSelectedItem()).toString())
        {
            case "Piano":
                jButton1.requestFocus();
                jLabel3.setIcon(null);
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piano.jpg"))); 
                jPanel1.add(jLabel1);
                jLabel1.setBounds(6, 4, 144, 148);
                break;
            case "Guitar":
                jButton1.requestFocus();
                jLabel1.setIcon(null);
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitar.jpg"))); // NOI18N
                jPanel1.add(jLabel3);
                jLabel3.setBounds(376, 4, 144, 144);
                break;
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        if(userinfo.Search(jTextField1.getText(), jTextField2.getText()))
        {
            jComboBox1.setVisible(true);
            jComboBox2.setVisible(true);
            jButton13.setVisible(true);
        }
        else
            jDialog2.setVisible(true);
        jDialog1.dispose();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        jDialog2.dispose();
    }//GEN-LAST:event_jButton16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Piano_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Piano_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Piano_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Piano_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Piano_GUI().setVisible(true);
                } catch (MidiUnavailableException ex) {
                    Logger.getLogger(Piano_GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
        
    }

    @Override
    public void keyPressed(KeyEvent e) {
        int c = e.getKeyCode();
        if (c == KeyEvent.VK_CAPS_LOCK)
        {
            if (Sustain == true)
            {
                Sustain = false;
                jToggleButton1.getModel().setSelected(false);
            }
            else if (Sustain == false)
            {
                Sustain = true;
                jToggleButton1.getModel().setSelected(true);
            }
        }
        
        
        if(c == KeyEvent.VK_Q)
        {
            jButton1.setBackground(Color.black);
                midisound.play("C",Sustain);
        }
        else if(c == KeyEvent.VK_W)
        {
            jButton2.setBackground(Color.black);
                midisound.play("D",Sustain);
        }
        else if(c == KeyEvent.VK_E)
        {
            jButton3.setBackground(Color.black);
                midisound.play("E",Sustain);
        }
        else if(c == KeyEvent.VK_R)
        {
            jButton4.setBackground(Color.black);
            midisound.play("F",Sustain);
        }
        else if(c == KeyEvent.VK_T)
        {
            jButton5.setBackground(Color.black);
            midisound.play("G",Sustain);
        }
        else if(c == KeyEvent.VK_Y)
        {
            jButton6.setBackground(Color.black);
            midisound.play("A",Sustain);
        }
        else if(c == KeyEvent.VK_U)
        {
            jButton7.setBackground(Color.black);
            midisound.play("B",Sustain);
        }
        else if(c == KeyEvent.VK_2)
        {
            jButton8.setBackground(Color.gray);
            midisound.play("Cs",Sustain);
        }
        else if(c == KeyEvent.VK_3)
        {
            jButton9.setBackground(Color.gray);
            midisound.play("Ds",Sustain);
        }
        else if(c == KeyEvent.VK_5)
        {
            jButton10.setBackground(Color.gray);
            midisound.play("Fs",Sustain);
        }
        else if(c == KeyEvent.VK_6)
        {
            jButton11.setBackground(Color.gray);
            midisound.play("Gs",Sustain);
        }
        else if(c == KeyEvent.VK_7)
        {
            jButton12.setBackground(Color.gray);
            midisound.play("As",Sustain);
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
        jButton1.setBackground(null);
        jButton2.setBackground(null);
        jButton3.setBackground(null);
        jButton4.setBackground(null);
        jButton5.setBackground(null);
        jButton6.setBackground(null);
        jButton7.setBackground(null);
        jButton8.setBackground(Color.black);
        jButton9.setBackground(Color.black);
        jButton10.setBackground(Color.black);
        jButton11.setBackground(Color.black);
        jButton12.setBackground(Color.black);
        
    }

    @Override
    public void mouseClicked(MouseEvent e) {    
    }

    @Override
    public void mousePressed(MouseEvent e) {
              
         if (jToggleButton1.getModel().isSelected() == true)
            Sustain = true;
        else Sustain = false;
        
        
        if(e.getSource().equals(jButton1))
        {
            jButton1.setBackground(Color.black);
            midisound.play("C",Sustain);
        }
        else if(e.getSource().equals(jButton2))
        {
            jButton2.setBackground(Color.black);
            midisound.play("D",Sustain);
        }
        else if(e.getSource().equals(jButton3))
        {
            jButton3.setBackground(Color.black);
            midisound.play("E",Sustain);
        }
        else if(e.getSource().equals(jButton4))
        {
            jButton4.setBackground(Color.black);
            midisound.play("F",Sustain);
        }
        else if(e.getSource().equals(jButton5))
        {
            jButton5.setBackground(Color.black);
            midisound.play("G",Sustain);
        }
        else if(e.getSource().equals(jButton6))
        {
            jButton6.setBackground(Color.black);
            midisound.play("A",Sustain);
        }
        else if(e.getSource().equals(jButton7))
        {
            jButton7.setBackground(Color.black);
            midisound.play("B",Sustain);
        }
        else if(e.getSource().equals(jButton8))
        {
            jButton8.setBackground(Color.gray);
            midisound.play("Cs",Sustain);
        }
        else if(e.getSource().equals(jButton9))
        {
            jButton9.setBackground(Color.gray);
            midisound.play("Ds",Sustain);
        }
        else if(e.getSource().equals(jButton10))
        {
            jButton10.setBackground(Color.gray);
            midisound.play("Fs",Sustain);
        }
        else if(e.getSource().equals(jButton11))
        {
            jButton11.setBackground(Color.gray);
            midisound.play("Gs",Sustain);
        }
        else if(e.getSource().equals(jButton12))
        {
            jButton12.setBackground(Color.gray);
            midisound.play("As",Sustain);
        }
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        jButton1.setBackground(null);
        jButton2.setBackground(null);
        jButton3.setBackground(null);
        jButton4.setBackground(null);
        jButton5.setBackground(null);
        jButton6.setBackground(null);
        jButton7.setBackground(null);
        jButton8.setBackground(Color.black);
        jButton9.setBackground(Color.black);
        jButton10.setBackground(Color.black);
        jButton11.setBackground(Color.black);
        jButton12.setBackground(Color.black);
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }
}
